-- Add the flag column
ALTER TABLE public.stores ADD COLUMN IF NOT EXISTS in_nx_network boolean DEFAULT false;

-- Stage the NX retailer names in a temp table
CREATE TEMP TABLE nx_retailers (raw text);

INSERT INTO nx_retailers (raw) VALUES
  ('123-reg.co.uk'),
  ('1pmobile'),
  ('24|7 Boiler Cover'),
  ('24|7 Breakdown Cover'),
  ('2bTanned'),
  ('3D Prima UK'),
  ('3Retro Football'),
  ('883 Police'),
  ('AA UK Breakdown'),
  ('Above & Below Jewellery'),
  ('Ace Airport Parking'),
  ('Active Era'),
  ('Activity Superstore'),
  ('adidas'),
  ('Advanced MP3 Player'),
  ('AEG Home Appliance'),
  ('AEG Parts and Accessories'),
  ('Agent Provocateur'),
  ('Air India'),
  ('Airparks'),
  ('Airport Parking Luton (UK)'),
  ('AKKO'),
  ('Alamo'),
  ('Alfa Travel Ltd.'),
  ('Alibaba'),
  ('AliExpress UK'),
  ('allbeauty'),
  ('Allpowers'),
  ('AllSaints'),
  ('Amazon Cashback'),
  ('Ancestry UK'),
  ('Angel and Rocket'),
  ('Animal'),
  ('Anine Bing'),
  ('Anker'),
  ('AnkerMake'),
  ('AnkerSOLIX'),
  ('Ann Summers'),
  ('Annoushka'),
  ('Anthropologie'),
  ('Antler'),
  ('Antonioli'),
  ('anyvan'),
  ('AO.com'),
  ('Aosom'),
  ('APH - Airport Parking & Hotels'),
  ('Appleyard Flowers'),
  ('Appliance City'),
  ('Appliances Direct'),
  ('Arabian Adventures'),
  ('Archiproducts'),
  ('Arena Flowers'),
  ('Arena Hotels'),
  ('Argento'),
  ('Argus Car hire'),
  ('Ariat'),
  ('Arlo Security UK'),
  ('Armani Beauty UK'),
  ('Arran - Sense of Scotland'),
  ('Arsenal Direct'),
  ('ARTAH'),
  ('Artfinder'),
  ('ASDA Groceries'),
  ('ASOS'),
  ('Aspinal of London'),
  ('Aspire Furniture LTD'),
  ('Aston Villa Store'),
  ('Astrid & Miyu'),
  ('ASUS'),
  ('ATG Tickets'),
  ('Atkin & Thyme'),
  ('AttractionTickets.com'),
  ('Audials Windows Software'),
  ('Auras Insurance'),
  ('Aurora Skin'),
  ('Autodesk Store UK'),
  ('Autodoc'),
  ('AutoEurope'),
  ('Avant Skincare'),
  ('Avanti Travel Insurance'),
  ('Aveda'),
  ('Avis'),
  ('Away Resorts'),
  ('BabyBjorn'),
  ('Baker Ross'),
  ('Bakerdays UK'),
  ('Balsam Hill'),
  ('Banggood.com'),
  ('Bank Switch Offers'),
  ('Barc London'),
  ('Barcelo'),
  ('Barker & Stonehouse'),
  ('Beauty Flash'),
  ('Beauty The Shop'),
  ('Beauty Works'),
  ('Beaverbrooks'),
  ('Bedding Envy'),
  ('Beelivery'),
  ('Beerhunter'),
  ('Begg Shoes'),
  ('Beko'),
  ('Belkin'),
  ('Belle Lingerie'),
  ('Belleek UK'),
  ('Belstaff'),
  ('Bemz UK'),
  ('Ben Sherman'),
  ('Benefit'),
  ('Berghaus'),
  ('Bern Helmets'),
  ('Best Cashback Websites & Apps in the UK'),
  ('Best Direct UK'),
  ('Best Gym Equipment'),
  ('Best Student Discount Apps'),
  ('Best UK Cashback Debit Cards'),
  ('Better Bathrooms'),
  ('Beyond Nine'),
  ('Big Bus Tours'),
  ('BiGDUG'),
  ('BigGreenSmile'),
  ('Billionaire Boys Club'),
  ('Bio-Synergy'),
  ('BioGaia'),
  ('Biovea UK'),
  ('Blacks'),
  ('Blake Mill'),
  ('Blinds Direct Online'),
  ('Bling King London'),
  ('Bloch UK Ltd'),
  ('Bloom & Wild'),
  ('Bloom Cabin'),
  ('Bloomingdale&#039;s'),
  ('Blossoming Flowers and Gifts'),
  ('Blue Elephant'),
  ('Blue Tomato'),
  ('Bluebella'),
  ('Bluecrest'),
  ('Bluefin SUP'),
  ('Boden'),
  ('Bodybuilding Warehouse'),
  ('Bodykind'),
  ('Bodywel ebike'),
  ('Bogner'),
  ('Bonmarche'),
  ('Boody'),
  ('BooHoo.com'),
  ('boohooMan.com'),
  ('Boots'),
  ('Boots Kitchen Appliances'),
  ('Boots Photo'),
  ('Boutique Camping'),
  ('Boux Avenue'),
  ('Bower Collective'),
  ('Bows Boutiques'),
  ('BrandAlley'),
  ('Brands Deluxe'),
  ('Breeze eSim UK'),
  ('Brewers'),
  ('British & Irish Lions'),
  ('Britt&#039;s Superfoods'),
  ('Broadway Travel'),
  ('Brora'),
  ('Browns Fashion'),
  ('Buff Skincare'),
  ('Bugaboo'),
  ('Building Materials'),
  ('bulk'),
  ('BullyBillows'),
  ('Bunches.co.uk'),
  ('Burgess Pet Care'),
  ('Burleigh'),
  ('Burton'),
  ('Butterworth&#039;s'),
  ('Buture'),
  ('Buy Sheds Direct'),
  ('Buyagift'),
  ('Buybestgear'),
  ('Buycarparts'),
  ('Cabin Zero'),
  ('Cadbury Gifts Direct'),
  ('Cadense UK'),
  ('Caledonian Travel'),
  ('Calendar Club'),
  ('Calvin Klein'),
  ('Cambridge Audio'),
  ('Cambridge Mask'),
  ('Camera World'),
  ('Camilla'),
  ('Camper'),
  ('Canadian Affair'),
  ('Candy Kittens'),
  ('Canon'),
  ('Canterbury'),
  ('Car Parts 4 Less'),
  ('cardfactory'),
  ('Careline365'),
  ('Carl Scarpa'),
  ('Carrentals.co.uk'),
  ('Cartridge Monkey'),
  ('Casa Bella Furniture'),
  ('Case Luggage'),
  ('Cashback Comparison Tool'),
  ('Cashback Debit Cards'),
  ('Cashback Stacking Guide'),
  ('Cashback Tracking Guide'),
  ('Casio'),
  ('Cass Art'),
  ('Cast in Style'),
  ('Castore'),
  ('Cazaar'),
  ('CCL'),
  ('CCleaner'),
  ('Ceiling Tiles'),
  ('CEWE'),
  ('Champions Travel'),
  ('Chapelle'),
  ('Chargrilled t-shirts'),
  ('Charles & Keith'),
  ('Charles Clinkard'),
  ('Charles Tyrwhitt'),
  ('Charlotte Tilbury'),
  ('Chelsea Florals'),
  ('Chelsea Megastore'),
  ('Chelsea Peers'),
  ('Cherry Lane Garden Centres'),
  ('Chesca Direct'),
  ('Chicco'),
  ('Chicme UK'),
  ('Childrensalon'),
  ('ChildrensFootball.com'),
  ('Childsplay Clothing'),
  ('Chillblast'),
  ('CHO Fashion & Lifestyle'),
  ('Choc on Choc'),
  ('Chocolate Trading Company'),
  ('Choice Furniture Superstore'),
  ('Christies Direct'),
  ('Christmas Tree World'),
  ('Christophe Robin'),
  ('Christow'),
  ('Christy'),
  ('Chunk of Devon'),
  ('CIARRA UK'),
  ('Circle Fashion'),
  ('City Cruises'),
  ('City Plumbing'),
  ('Clarins'),
  ('Click Basin'),
  ('Click4Gap'),
  ('Clifton Cameras'),
  ('Clinique'),
  ('Clogau'),
  ('Club L London'),
  ('Club Med'),
  ('Co-op Food'),
  ('Coast'),
  ('Cocunat'),
  ('Coffee Friend'),
  ('Columbia Sportswear'),
  ('Compare Supermarket Cashback Rates'),
  ('Complete Cashback Guide'),
  ('Conrad Electronic'),
  ('ContactLenses.co.uk'),
  ('Contiki'),
  ('Coopers of Stortford'),
  ('Corendon Airlines'),
  ('Corsair'),
  ('Cos UK'),
  ('Cosi Home'),
  ('Cosmetify'),
  ('Cosori UK'),
  ('Cost Cutters UK'),
  ('Costway UK'),
  ('Cosyfeet'),
  ('Cotswold Outdoor'),
  ('Cotton On'),
  ('Cotton Traders'),
  ('Cottsbury'),
  ('Counter Culture Store'),
  ('CovingandMouldings'),
  ('Coway UK'),
  ('Cox and Cox'),
  ('Crampton and Moore'),
  ('Crazy Kangaroo'),
  ('Create'),
  ('Crew Clothing'),
  ('Cricut'),
  ('Crocs'),
  ('Crystal Ski - National Express'),
  ('Cult Beauty'),
  ('Cupshe UK'),
  ('Curious Egg'),
  ('Currys'),
  ('Currys Partsmaster'),
  ('Custom Controllers'),
  ('Cutter and Squidge'),
  ('CyberGhost VPN'),
  ('Damart'),
  ('DAME'),
  ('Dare2b'),
  ('Darlings of Chelsea'),
  ('Dartington Crystal'),
  ('Dash Water'),
  ('Daylesford Organic'),
  ('DB Journey'),
  ('Debenhams'),
  ('Decathlon UK'),
  ('Decorative Aggregates'),
  ('Decree'),
  ('Deesse Pro'),
  ('Delilah Cosmetics'),
  ('Deliveroo'),
  ('Dell'),
  ('Dell Outlet'),
  ('Dell Refurbished'),
  ('Delonghi'),
  ('Dents Gloves'),
  ('Dermatica'),
  ('Design My World'),
  ('Designer Wear'),
  ('Desktronic'),
  ('DFB-Fanshop'),
  ('DFDS Seaways'),
  ('Direct 365'),
  ('Direct Blinds'),
  ('Direct Cosmetics'),
  ('Direct Ferries'),
  ('Direct Fireplaces'),
  ('Direct Heating Spares'),
  ('Direct Stoves'),
  ('Direct-Running UK'),
  ('Discount Experts'),
  ('Discount Golf Store'),
  ('Discounted Sunglasses'),
  ('Discover Cars'),
  ('DisneyStore'),
  ('Dobell'),
  ('Domino&#039;s'),
  ('Don&#039;t buy her flowers'),
  ('Door Superstore'),
  ('Dorothy Perkins'),
  ('Dorset Hideaways'),
  ('Doulton'),
  ('Dower & Hall'),
  ('Downtown Stores'),
  ('Drainage Superstore'),
  ('Drench'),
  ('drinkstuff.com'),
  ('DrinkWell'),
  ('dryrobe UK'),
  ('Dulux'),
  ('Dune London'),
  ('Dunelm'),
  ('Dusk Lights'),
  ('DYU Ebike'),
  ('Early Learning Centre'),
  ('Earn Money Top 10 Sites/Apps'),
  ('Earths Secrets'),
  ('Eastpak'),
  ('easyHotel'),
  ('easyJet Holidays'),
  ('Easylife'),
  ('EasySim'),
  ('Easyspace'),
  ('eBay'),
  ('Ebuyer'),
  ('ECatering'),
  ('Echelon Fit UK'),
  ('Ecovacs'),
  ('Edmunds Cocktails'),
  ('eDreams'),
  ('EE Tech & Gaming'),
  ('Efectiv Nutrition'),
  ('eFlorist UK'),
  ('EGO'),
  ('EKO Home'),
  ('Ekster'),
  ('Eleano’s Gallery'),
  ('Electrical Discount UK'),
  ('Electrical World'),
  ('Electricshop'),
  ('Electrolux'),
  ('Elegant Showers UK'),
  ('Elemis'),
  ('Eleonora Bonucci'),
  ('ELGATO'),
  ('Elizabeth Arden'),
  ('Ellesse'),
  ('Emergency Assist'),
  ('Emirates'),
  ('Emma'),
  ('Emma Bridgewater'),
  ('Emma Hardie'),
  ('Emmy London'),
  ('EMP'),
  ('Endgame Gear'),
  ('England FA Shop'),
  ('England Rugby Store'),
  ('English Heritage Membership'),
  ('English Heritage Shop'),
  ('Enjoy the Wood'),
  ('Enjoy Travel'),
  ('Enterprise Rent-A-Car'),
  ('Envirofone'),
  ('EPD'),
  ('Equi London'),
  ('Ernest Jones'),
  ('ESE Direct'),
  ('ESET UK'),
  ('ESPA Skincare'),
  ('Estee Lauder'),
  ('Ethical Superstore'),
  ('Ethiopian Airlines'),
  ('Etihad Airways'),
  ('Etihad Holidays'),
  ('Eufy'),
  ('Euro Car Parts'),
  ('Europcar'),
  ('Evan Evans Tours'),
  ('Event Decor Shop'),
  ('Eventim'),
  ('Everton'),
  ('Evri – The new Hermes'),
  ('Evri International'),
  ('Expedia'),
  ('Explorer Travel Insurance'),
  ('Express Trainers'),
  ('F.Hinds Jewellers'),
  ('F1 Autocentres'),
  ('F1 Store'),
  ('Faace'),
  ('Fab Homes'),
  ('FabFinds'),
  ('Fabrique'),
  ('Face the Future'),
  ('Facetheory UK'),
  ('Faith Jewellers'),
  ('Fanatics'),
  ('Farah'),
  ('FARFETCH'),
  ('Farm Rio UK'),
  ('Farnell'),
  ('Fashion Addict'),
  ('Fashion Eyewear'),
  ('Fawkes Cycles'),
  ('Feather & Black (UK)'),
  ('Feel Good Contacts'),
  ('Fenty Beauty'),
  ('Fever'),
  ('Find Best Cashback Rates'),
  ('Find Me A Gift'),
  ('findmypast'),
  ('Fine Food Specialist'),
  ('Fiorucci'),
  ('Firebox.com'),
  ('First Choice'),
  ('Firsty'),
  ('FitFlop'),
  ('Fitimins'),
  ('Fitness Options'),
  ('Flanerie'),
  ('Flannels'),
  ('FlexiSpot'),
  ('Flixbus'),
  ('Flooring Revolution'),
  ('Flower Station Ltd'),
  ('flowerbx'),
  ('Flowers & Plants Co'),
  ('Flying Flowers'),
  ('FOCO'),
  ('FOLD Reformer'),
  ('Foot Locker UK'),
  ('Footshop'),
  ('Foreo'),
  ('Formula 1 Arcade'),
  ('Formulae Prescott'),
  ('Forth With Life'),
  ('Forthglade'),
  ('Fortnum and Mason'),
  ('Fossil'),
  ('Foxy Locks'),
  ('FragranceX.com'),
  ('Framed Works'),
  ('Fraser Hart'),
  ('Frasers'),
  ('Free Money Offers'),
  ('Free Soul'),
  ('Freedom Of Movement'),
  ('French Bedroom'),
  ('French Connection'),
  ('Frenchic Paint'),
  ('Frenzy Clothings'),
  ('Freshlick'),
  ('FSCS Coverage Checker'),
  ('Funky Pigeon'),
  ('Furniture Direct Online'),
  ('Furniture in Fashion'),
  ('Furniture Village'),
  ('Furniture123'),
  ('Furocity'),
  ('FutureLearn Limited'),
  ('G-SHOCK'),
  ('GAME'),
  ('Gamola Golf'),
  ('Ganni'),
  ('Garden by Waitrose & Partners'),
  ('Garden Furniture Centre'),
  ('Gardenesque'),
  ('Gardening Direct'),
  ('Gardenstone'),
  ('GatorTape'),
  ('Gatwick Holiday Parking'),
  ('GB Posters'),
  ('Geepas'),
  ('George at ASDA'),
  ('Get The Label'),
  ('Get-Paid-To Play Websites'),
  ('GetYourGuide'),
  ('Ghost'),
  ('Ghost Bikes'),
  ('GIA Fee Comparison'),
  ('Gift Card Cashback Comparison'),
  ('Give Me Cosmetics'),
  ('Glasses Direct'),
  ('Glenmuir'),
  ('Global Levels for GSF Car Parts'),
  ('Glow.co.uk'),
  ('Go Groopie'),
  ('Go Outdoors'),
  ('Goddiva'),
  ('Gold Boutique'),
  ('Goldsmiths'),
  ('Golf Gear Direct'),
  ('Gorgeous Shop'),
  ('Graham and Green'),
  ('Great Little Breaks'),
  ('Great Little Trading Company'),
  ('GreatBeanBags.com'),
  ('Green & Blacks'),
  ('Green Chef UK'),
  ('Green People'),
  ('Grenade'),
  ('Groomers'),
  ('Groupon UK'),
  ('Grow Money Best Savings Interest Rates'),
  ('Gtech'),
  ('H&M'),
  ('H&T Jewellery'),
  ('Habitat Escapes Ltd'),
  ('Habitat UK'),
  ('Hair Burst Limited'),
  ('Halfords'),
  ('Hamleys'),
  ('Happy Beds'),
  ('Happy Homeware'),
  ('Happyology'),
  ('Harfi'),
  ('Harper Collins'),
  ('Harts Of Stur'),
  ('Harvey Nichols'),
  ('Haven Holidays'),
  ('Hawes & Curtis'),
  ('Haws'),
  ('Heal&#039;s'),
  ('Health and Her'),
  ('Healthspan UK Elite'),
  ('Hedges Direct'),
  ('Heist Studios'),
  ('Hello Fresh'),
  ('Hello of Mayfair Furniture'),
  ('Herman Miller'),
  ('Herring Shoes'),
  ('HEYDUDE'),
  ('HiCCUP'),
  ('Hiro Worldwide Ltd'),
  ('HiSmile'),
  ('Hive Books'),
  ('Hobbs'),
  ('Hoka One One'),
  ('Holiday Autos'),
  ('Holiday Extras'),
  ('HolidayTaxis'),
  ('Holidu UK'),
  ('Holland and Barrett'),
  ('Home Fitness Code'),
  ('Homes & Villas by Marriott Bonvoy'),
  ('Homescapes'),
  ('Honor UK'),
  ('Hoover'),
  ('Host and Stay'),
  ('Hot Diamonds'),
  ('Hot Golf UK'),
  ('Hotels.com'),
  ('Hothair'),
  ('Hotpoint UK Appliances'),
  ('HP'),
  ('Huawei'),
  ('Hughes'),
  ('Hunkemoller UK'),
  ('Husqvarna'),
  ('Hyperice UK'),
  ('I Want One Of Those'),
  ('Iberia'),
  ('iCandy'),
  ('Iceland'),
  ('Ickle Bubba Ltd'),
  ('Iconic London'),
  ('Iglu Ski'),
  ('iHerb'),
  ('InfinityXinfinity'),
  ('Inov-8'),
  ('Insulation Superstore'),
  ('Insure & Go'),
  ('Interparcel'),
  ('InterRose'),
  ('Investing Offers'),
  ('iRobot'),
  ('iS Clinical'),
  ('ISA Fee Comparison'),
  ('Isango'),
  ('iStore'),
  ('IT Luggage'),
  ('Jacamo'),
  ('Jack Wolfskin UK'),
  ('Jackery'),
  ('Jam Golf'),
  ('Jane Plan'),
  ('Japspeed'),
  ('Java Whiskers'),
  ('JBL UK'),
  ('JD Sports'),
  ('JD Williams'),
  ('Jetpac'),
  ('Jigsaw'),
  ('JigsawPuzzle'),
  ('Jimmy Choo'),
  ('Joe Browns'),
  ('John Greed Jewellery'),
  ('Joseph'),
  ('Joseph Joseph'),
  ('JOY'),
  ('Jules B'),
  ('Julian Charles'),
  ('Just Eat'),
  ('Just Geek'),
  ('Just Sheepskin'),
  ('JustWears'),
  ('JustYou'),
  ('justyouroutfit'),
  ('K-Swiss'),
  ('Karcher'),
  ('Karen Millen'),
  ('Karl Lagerfeld'),
  ('Kaspersky'),
  ('Kaytea'),
  ('Kendamil'),
  ('Kenwood'),
  ('Kerastase'),
  ('Kettler Furniture'),
  ('Kickers'),
  ('Kiddies Kingdom'),
  ('Kiehl&#039;s'),
  ('Kiko'),
  ('KinKind'),
  ('Kipling UK'),
  ('Kitbox'),
  ('Kiwi.com'),
  ('KiwiCo'),
  ('Klass'),
  ('Klook'),
  ('Knickerbox'),
  ('Koo-di'),
  ('KRCS Apple Premium Reseller'),
  ('Kwik Fit'),
  ('KWM wines'),
  ('L&#039;AGENCE'),
  ('L&#039;Artisan Parfumeur'),
  ('L&#039;Occitane'),
  ('L&#039;OR'),
  ('La Redoute'),
  ('La Roche Posay'),
  ('Lacoste'),
  ('Laithwaites'),
  ('Lampandlight UK'),
  ('Lancome'),
  ('Land of Rugs'),
  ('Lands&#039; End UK'),
  ('Landscaping Superstore'),
  ('Laptops Direct'),
  ('lastminute.com'),
  ('Latest In Beauty'),
  ('Lavazza'),
  ('Lavish Alice Retail Ltd'),
  ('LazyPanda'),
  ('Le Col UK'),
  ('Le Specs'),
  ('Leader Online'),
  ('Leather Company'),
  ('Lebara Mobile'),
  ('Lee'),
  ('Leekes'),
  ('LEGO'),
  ('Legology'),
  ('Leisure Lakes Bikes'),
  ('Lemonade Dolls'),
  ('Lenovo UK'),
  ('Lenstore UK Contact Lenses'),
  ('Levi&#039;s'),
  ('LG'),
  ('Libernovo'),
  ('Liberty London'),
  ('Liforme'),
  ('Lights.co.uk'),
  ('Lights4Fun'),
  ('Lily Charmed'),
  ('Lindt'),
  ('Lindy Electronics'),
  ('Lite Stone'),
  ('Little Helper'),
  ('Little Lies'),
  ('Living and Home'),
  ('Living DNA'),
  ('Liz Earle'),
  ('Logitech'),
  ('Logitech G'),
  ('London Graphic Centre'),
  ('London Sock Company'),
  ('London Theatre Direct'),
  ('London Zoo'),
  ('Long Tall Sally'),
  ('LOOKFANTASTIC'),
  ('Looking Glass'),
  ('Looking4Parking'),
  ('Loop Earplugs'),
  ('Loop Mobile'),
  ('Lord Of The Beards'),
  ('Louche'),
  ('Lovat Parks'),
  ('Love the Sales'),
  ('Love To Dream'),
  ('loveholidays UK'),
  ('Lovehoney'),
  ('Lovell Sports'),
  ('LOVEtheatre'),
  ('Loving Foods'),
  ('LSA International'),
  ('Lucky2Go'),
  ('Luff Sleep'),
  ('Luke Roper'),
  ('Lulu Guinness'),
  ('lululemon'),
  ('Luxurious Look'),
  ('Luxury Cottages'),
  ('Lyle & Scott'),
  ('Macback'),
  ('MacFinder'),
  ('Macy&#039;s'),
  ('Magazines Direct'),
  ('Magee 1866'),
  ('Magic Madhouse'),
  ('MagicBreaks'),
  ('MAGIX'),
  ('MagsDirect'),
  ('Magzter'),
  ('Mahabis'),
  ('Mainline'),
  ('Majestic Wine'),
  ('Make My Blinds'),
  ('Malaysia Airlines'),
  ('Mamas & Papas'),
  ('Mammotion'),
  ('Manchester United'),
  ('ManoMano'),
  ('Maplin'),
  ('Mappin & Webb'),
  ('Marks and Spencer'),
  ('Marks Electricals'),
  ('Masdings'),
  ('Mastershoe'),
  ('Matalan'),
  ('Materials Market'),
  ('Mattress Online'),
  ('Mattressnextday'),
  ('Max Photo'),
  ('Maxi-Cosi'),
  ('MaxiNutrition'),
  ('McAfee'),
  ('Mcqueens Dairies'),
  ('MD London'),
  ('Medela'),
  ('Medino'),
  ('Mejuri'),
  ('Memory Foam Warehouse'),
  ('Merit Beauty'),
  ('Merrell'),
  ('Merry People'),
  ('Metalshop.com'),
  ('Michael Kors'),
  ('Miele'),
  ('Millets'),
  ('Miraclesuit'),
  ('MissPap'),
  ('Mitre'),
  ('MLB'),
  ('Moda in Pelle'),
  ('Moda Operandi'),
  ('Modmo'),
  ('Mojo'),
  ('Molton Brown'),
  ('Monopoly Lifesized - London (UK affiliates)'),
  ('Moonpig'),
  ('More&#8230;'),
  ('Morphy Richards'),
  ('Morrisons Grocery'),
  ('Motorsport Tickets'),
  ('Mountain Warehouse'),
  ('Move Pre-Workout'),
  ('MPB.com'),
  ('Muc-Off'),
  ('Mugler'),
  ('Munbyn UK'),
  ('Musement'),
  ('Music Magpie'),
  ('Mustard London'),
  ('Musto'),
  ('My 1st Years'),
  ('My Babiie'),
  ('My Motor World'),
  ('My Nintendo Store'),
  ('My Tool Shed'),
  ('MyFlowers'),
  ('MyHeritage'),
  ('Mylee'),
  ('MyMemory'),
  ('MyNextBike'),
  ('Myprotein'),
  ('MyTheresa'),
  ('mytyres.co.uk'),
  ('myvitamins'),
  ('Myzone'),
  ('MZ Skin'),
  ('Nadula'),
  ('Nails Inc'),
  ('Nars Cosmetics'),
  ('NastyGal UK'),
  ('National Express'),
  ('National Shower Spares'),
  ('National Tyres and Autocare'),
  ('Native Places'),
  ('Natural Collection'),
  ('Nature&#039;s Best'),
  ('Nature&#039;s Fix'),
  ('NBA Store'),
  ('Neal & Wolf'),
  ('Nearly Naked Veg'),
  ('Nere'),
  ('Nespresso'),
  ('New Balance'),
  ('New Era Cap'),
  ('New Look'),
  ('Newbridge Silverware'),
  ('Newmarket Holidays'),
  ('NFL Shop'),
  ('NHL Shop'),
  ('Niche Jewellery'),
  ('Nike'),
  ('Nikura'),
  ('Nip & Fab'),
  ('Nisbets'),
  ('Nkuku'),
  ('NO GUNK'),
  ('no7 Beauty'),
  ('Noble Panacea UK'),
  ('Nobody&#039;s Child'),
  ('Noobru'),
  ('NordVPN'),
  ('Norfolk Hideaways'),
  ('Norton'),
  ('Nothing Fishy'),
  ('Notino'),
  ('notonthehighstreet.com'),
  ('Numan'),
  ('Nutricircle'),
  ('NutriQuarter'),
  ('Oak&More'),
  ('Oakley'),
  ('Oasis'),
  ('Ocado'),
  ('Ocean Bottle'),
  ('Octopus Energy Tracker Comparison'),
  ('Offer Tracking Guide'),
  ('Offers Partner Offers'),
  ('Office Furniture Online'),
  ('Office Monster'),
  ('Office Shoes'),
  ('Office Stationery'),
  ('OKA'),
  ('Oliver Sweeney Trading Limited'),
  ('Olivia & Pearl'),
  ('Olivia Burton'),
  ('OLPRO'),
  ('OMNES'),
  ('On The Beach'),
  ('onefinestay'),
  ('OnePlus'),
  ('Online Home Shop'),
  ('Opodo UK'),
  ('OptiBac Probiotics'),
  ('OptimallyMe'),
  ('Optimum Nutrition'),
  ('Oral B'),
  ('Original BTC'),
  ('Original Penguin'),
  ('Oscar & Hooch'),
  ('Otterbox'),
  ('OTTY Sleep'),
  ('Overclockers UK'),
  ('Oxfam Online Shop'),
  ('Oxford Online Pharmacy'),
  ('Pagazii'),
  ('Panasonic'),
  ('Panda Security'),
  ('Pandora'),
  ('Parcel2go'),
  ('Paria'),
  ('Parkdean Resorts'),
  ('ParkVia'),
  ('PartyLite'),
  ('Passenger'),
  ('PatPat UK'),
  ('Paul Smith'),
  ('PAWD DRINKS'),
  ('Paying Too Much'),
  ('Peace Out Skincare'),
  ('Peachaus Lounge'),
  ('Peacocks'),
  ('Peeko'),
  ('Penelope Chilvers'),
  ('Penhaligon&#039;s UK'),
  ('Percy and Reed'),
  ('Peregrine Clothing'),
  ('Perfect Pet'),
  ('Perfume Click'),
  ('PerriconeMD'),
  ('Pet Drugs Online'),
  ('Petgevity'),
  ('Petlibro'),
  ('Pets at Home'),
  ('Pets Villa'),
  ('Peugeot Saveurs'),
  ('PGL Travel'),
  ('Pharmacy First'),
  ('Pharmacy2U'),
  ('Pharmacy2u Shop'),
  ('Phase Eight'),
  ('Philip Kingsley'),
  ('Philips'),
  ('Philips Hue UK'),
  ('Photobox'),
  ('Picniq'),
  ('Pizza Hut'),
  ('PLAUD UK'),
  ('PlayPress Toys'),
  ('Plumbing Superstore'),
  ('Plumbworld'),
  ('Pod Point'),
  ('Polar UK'),
  ('Polarn O Pyret'),
  ('Polished London'),
  ('Poltronesofa at ScS'),
  ('Pond5'),
  ('Pondkeeper'),
  ('Pong Cheese'),
  ('Pooch and Mutt'),
  ('POPSTORE'),
  ('Postmymeds'),
  ('Posturite'),
  ('PoundFun'),
  ('Power Tools Direct'),
  ('PRC Direct'),
  ('Premier Inn at Home'),
  ('Prep Kitchen'),
  ('Prescription Doctor'),
  ('Prestige'),
  ('PrettyLittleThing'),
  ('Price Crash Furniture'),
  ('Printerinks'),
  ('PrinterPix UK'),
  ('Printrendy'),
  ('Pro Breeze'),
  ('ProCook'),
  ('Professional Building Supplies'),
  ('Prop Options'),
  ('Protein Works'),
  ('Proviz'),
  ('Prungo'),
  ('Public Desire'),
  ('Pull & Bear'),
  ('Puma'),
  ('Pure Beauty'),
  ('Pure Leisure Group'),
  ('Purina UK'),
  ('Purple Parking'),
  ('Q-Park'),
  ('Qskinz'),
  ('QVC'),
  ('Rabbie&#039;s Tours'),
  ('Radley'),
  ('Railcard'),
  ('RAJAPACK UK'),
  ('Ralph Lauren'),
  ('Ram Golf'),
  ('Ramsdens Jewellery'),
  ('Rangers FC Store'),
  ('Rapid'),
  ('Rascal Clothing'),
  ('RattanTree'),
  ('Raw Denim'),
  ('Ray Ban'),
  ('Real Food Hub'),
  ('Receipt Scanning Apps'),
  ('Red Funnel'),
  ('Red Letter Days'),
  ('Redbubble'),
  ('Reef Sandals'),
  ('Refer a Friend Offers'),
  ('Regal Fish'),
  ('Regatta'),
  ('Reiss'),
  ('Reliant'),
  ('Rem-Fit'),
  ('Renogy'),
  ('ReservAway'),
  ('Reverse Life'),
  ('RevitaLash'),
  ('Revive Active'),
  ('RISE coffee box'),
  ('River Island UK'),
  ('Riverford'),
  ('Riviera Travel'),
  ('Roamwild Products'),
  ('Robert Dyas'),
  ('Roborock UK'),
  ('Rockahula Kids'),
  ('Rohan'),
  ('Roksanda'),
  ('Roofing Superstore'),
  ('Roseland Furniture'),
  ('Rosetta Stone'),
  ('Routledge'),
  ('Rox'),
  ('Royal Doulton'),
  ('Royalbathrooms'),
  ('RS Components'),
  ('RSPB'),
  ('Rugs Direct'),
  ('Runners Need'),
  ('Ryman'),
  ('Ryobi'),
  ('Saily'),
  ('Sainsburys Groceries Online'),
  ('Saltrock'),
  ('SamBoat UK'),
  ('Samsung'),
  ('Samuel Johnston'),
  ('Sans Matin'),
  ('Saucony'),
  ('Save Money Best Cashback Apps'),
  ('Savers'),
  ('Savile Row Company'),
  ('SC Nutra'),
  ('Scandiborn'),
  ('Scholastic'),
  ('Schuh'),
  ('Scott Direct'),
  ('Scottish Fine Soaps UK'),
  ('Scottsdale Golf'),
  ('Scribbler'),
  ('Scrimpr Offer Search Engine'),
  ('Scrimpr Offer Search Engine (USA)'),
  ('Sealions'),
  ('Sealskinz'),
  ('Secret Flight Club'),
  ('Secret Sales'),
  ('SecretStays.co.uk'),
  ('See Tickets'),
  ('Sekonda'),
  ('Selections'),
  ('Selfridges'),
  ('Sensilab'),
  ('Sephora'),
  ('Serena Bute'),
  ('Serenata Flowers'),
  ('Servers Direct'),
  ('SGS Engineering'),
  ('SHEIN'),
  ('Sigma Sports'),
  ('SikSilk'),
  ('Silentnight'),
  ('Simba Sleep'),
  ('Simon Jersey'),
  ('Simple Clothing'),
  ('Simplisafe'),
  ('Simply Be'),
  ('Simply Business UK'),
  ('Simply Meds'),
  ('Simply Supplements'),
  ('SIPP Fee Comparison'),
  ('Sir Gordon Bennett'),
  ('Siren Craft Brew'),
  ('Skechers'),
  ('Ski France'),
  ('Skin Deep UK'),
  ('Skinners.cc'),
  ('Skinnydip'),
  ('SkyParkSecure'),
  ('Slam Jam'),
  ('Slaters'),
  ('Sleep Hubs'),
  ('Slimming World Kitchen'),
  ('Slurp'),
  ('Small Batch Coffee Roasters'),
  ('SmartBuyGlasses'),
  ('Smooth Move'),
  ('Snapfish'),
  ('Snaptrip'),
  ('Snow + Rock'),
  ('Snow Rental'),
  ('Snuz'),
  ('Soak and Sleep'),
  ('Sock Shop'),
  ('Sofa Club'),
  ('Sony'),
  ('Sorel'),
  ('Soundcore'),
  ('SpaBreaks'),
  ('Space NK'),
  ('Spartan'),
  ('Spartoo.co.uk'),
  ('SpaSeekers'),
  ('Sport and Leisure UK'),
  ('Sports Ball Shop'),
  ('Spotahome'),
  ('Spotlight Oral Care'),
  ('Standout'),
  ('Stanley 1913'),
  ('Stansted Airport Parking'),
  ('startriteshoes.com'),
  ('Startselect'),
  ('Stock Must Go'),
  ('StockX'),
  ('Stolt'),
  ('StrawberryNET'),
  ('Stress Free Car Rental'),
  ('Stretch It Body Jewellery'),
  ('Stuart Trevor'),
  ('Stuart Weitzman'),
  ('Stuarts London'),
  ('StubHub'),
  ('Stylevana'),
  ('Suit Direct'),
  ('Sunglass Hut'),
  ('Sunshine.co.uk'),
  ('Sunspel'),
  ('Superdrug'),
  ('Superdry'),
  ('Supermarket Cashback'),
  ('Supplement Hub'),
  ('Support Scrimpr'),
  ('Surfshark'),
  ('Survey Apps (Mobile)'),
  ('Survey Websites (Mobile &#038; Desktop)'),
  ('Suttons'),
  ('Swallow'),
  ('Sway Hair Extensions'),
  ('Sweatband'),
  ('Sweaty Betty'),
  ('Swoon London'),
  ('tabletennis365'),
  ('Tado'),
  ('Tap Warehouse'),
  ('TASCHEN'),
  ('Tassimo'),
  ('TBCo'),
  ('Tech Trade'),
  ('Temple Spa'),
  ('Tempur'),
  ('TEMU'),
  ('Tena'),
  ('TENZING Natural energy'),
  ('Terravision'),
  ('Terry&#039;s Fabrics'),
  ('Tesco F&F'),
  ('Tesco Groceries'),
  ('Tesco MP'),
  ('Tessabit Stores'),
  ('Teva'),
  ('TFNC'),
  ('TGJones'),
  ('The Big Phone Store'),
  ('The Body Shop'),
  ('The British Hamper Company'),
  ('The British Newspaper Archive'),
  ('The Cake Decorating Company'),
  ('The DoubleF'),
  ('The Entertainer'),
  ('The Fashion Square UK'),
  ('The Fast 800'),
  ('The Fine Bedding Company'),
  ('The Fragrance Counter'),
  ('The Fragrance Shop'),
  ('The Game Collection'),
  ('The Gift Experience'),
  ('The Gym Group'),
  ('The Gym King Ltd'),
  ('The Happy Puzzle Company'),
  ('The Independent Pharmacy'),
  ('The Inn Collection Group'),
  ('The IT Bay'),
  ('The Jewellery Channel'),
  ('The Knitting Network'),
  ('The Minifigure Store'),
  ('The Natural Africa'),
  ('The Nursery Store'),
  ('The Oodie UK'),
  ('The Organic Pharmacy'),
  ('The Outnet'),
  ('The Paint Shed'),
  ('The Perfume Shop'),
  ('The Posh Shed Company'),
  ('The Radiator Warehouse'),
  ('The Range'),
  ('The Safe Shop'),
  ('The Scotch Malt Whisky Society'),
  ('The Somerset Toiletry Co'),
  ('The Spark Company'),
  ('The Sports Edit'),
  ('The Towel Shop'),
  ('The Underfloor Heating Store'),
  ('The View from The Shard (UK)'),
  ('Theatre Tickets Direct'),
  ('Thompson & Morgan'),
  ('Thorntons'),
  ('Thortful'),
  ('Threadbare'),
  ('Tickadoo'),
  ('Ticketmaster'),
  ('Ticketmaster Theatre'),
  ('Timberland'),
  ('Tiqets'),
  ('Titleist'),
  ('TLC Sport'),
  ('Toby Tiger'),
  ('Together Health'),
  ('Tokyo Laundry'),
  ('Tommy Hilfiger'),
  ('Tools Cheap Direct Debit'),
  ('Toolstation UK'),
  ('Topshop Topman'),
  ('Torres Novas'),
  ('TORRO'),
  ('Tory Burch'),
  ('Totes Isotoner'),
  ('Tough Mudder'),
  ('Tousains'),
  ('Tower London UK'),
  ('Townhouse Blankets'),
  ('TP Toys'),
  ('Trade Price Flues'),
  ('Trafalgar'),
  ('Trail'),
  ('Trainline'),
  ('TrainPal'),
  ('TransPennine Express'),
  ('Transport For Wales'),
  ('Travel Insurance 4 Medical'),
  ('Travel Insurance Saver'),
  ('Travelodge'),
  ('Travelpro'),
  ('TravelSupermarket - Car Hire'),
  ('Travelsupermarket - Travel Insurance'),
  ('Travis Perkins'),
  ('Treatwell'),
  ('Tredz'),
  ('Tree2mydoor'),
  ('Trek-Expert'),
  ('Trilogy Stores'),
  ('Trimming Shop'),
  ('Trip.com'),
  ('Trollbeads'),
  ('Tru-Diamonds'),
  ('True Image'),
  ('Tui - National Express'),
  ('TV Cables'),
  ('Twinings Teashop'),
  ('Two Face Aesthetics'),
  ('TYMO Beauty'),
  ('Typo'),
  ('Tyre Shopper'),
  ('Tyres UK'),
  ('UGG'),
  ('UK Breakaways'),
  ('UK Office Direct Limited'),
  ('Ukmeetandgreet.com'),
  ('Ulike UK'),
  ('Under Armour'),
  ('unineed'),
  ('UNNDR'),
  ('UNOde50'),
  ('UPERFECT'),
  ('ur'),
  ('Urban Outfitters'),
  ('User Testing Websites'),
  ('Using Multiple Cashback Methods at the Same Time'),
  ('Vakole'),
  ('Vans'),
  ('Venchi'),
  ('Vertbaudet'),
  ('Very'),
  ('viagogo'),
  ('Viator a Tripadvisor company'),
  ('Viking'),
  ('Vinyl Castle'),
  ('VioVet'),
  ('Virgin Atlantic Airways'),
  ('Virgin Balloon Flights'),
  ('Virgin Experience Days'),
  ('Virgin Holidays'),
  ('Virtual College'),
  ('Vision Express'),
  ('VisitBritain'),
  ('VistaPrint'),
  ('VitaBright'),
  ('VIVE'),
  ('Vivo Life'),
  ('VIVOMED'),
  ('VO'),
  ('Vocalzone'),
  ('Vrbo'),
  ('Wallis'),
  ('Walt Disney Travel Company'),
  ('Warehouse'),
  ('Warehouse Wines'),
  ('Warrior'),
  ('Waterdropfilter'),
  ('Waterford'),
  ('Wedgwood'),
  ('wegottickets.com'),
  ('WeightWorld UK'),
  ('Weird Fish'),
  ('Welding & Welder'),
  ('Westminster Stone'),
  ('Whistles'),
  ('Who Gives A Crap'),
  ('Wholesale Domestic'),
  ('Wickes'),
  ('Wide Fit Shoes'),
  ('Wild & Stone'),
  ('Wild Cosmetics'),
  ('WildBounds'),
  ('William May'),
  ('William Wood'),
  ('Winstons Beds'),
  ('Wish'),
  ('Wonderbra'),
  ('Wood Finishes Direct UK'),
  ('Woodyatt Curtains'),
  ('World of Books'),
  ('Wowcher'),
  ('Wrangler UK'),
  ('WWE Shop'),
  ('Wynsors'),
  ('Xiaomi'),
  ('XSHRED'),
  ('xTool'),
  ('XY London'),
  ('Yazio'),
  ('YouGarden'),
  ('YourParkingSpace'),
  ('Yours Clothing UK'),
  ('YourSurprise'),
  ('YourZooki'),
  ('YSL Beauty UK'),
  ('YuMOVE'),
  ('Zanussi'),
  ('Zavvi'),
  ('Zebra Golf'),
  ('Zen Hotels'),
  ('Zest Car Rental'),
  ('Zooplus'),
  ('Zwilling UK');

-- Build a normalised key for both sides and match
-- Normalisation: lowercase, strip non-alphanumerics, collapse spaces
UPDATE public.stores AS s SET in_nx_network = true
WHERE EXISTS (
  SELECT 1 FROM nx_retailers n
  WHERE regexp_replace(lower(n.raw), '[^a-z0-9]', '', 'g')
      = regexp_replace(lower(s.name), '[^a-z0-9]', '', 'g')
);

-- Also try a "contains" match for things like "ASDA Groceries" → "Asda"
UPDATE public.stores AS s SET in_nx_network = true
WHERE in_nx_network = false
  AND length(s.name) >= 4
  AND EXISTS (
    SELECT 1 FROM nx_retailers n
    WHERE regexp_replace(lower(n.raw), '[^a-z0-9]', '', 'g')
        LIKE '%' || regexp_replace(lower(s.name), '[^a-z0-9]', '', 'g') || '%'
       OR regexp_replace(lower(s.name), '[^a-z0-9]', '', 'g')
        LIKE '%' || regexp_replace(lower(n.raw), '[^a-z0-9]', '', 'g') || '%'
  );

SELECT count(*) FILTER (WHERE in_nx_network) AS nx_partners,
       count(*) FILTER (WHERE NOT in_nx_network) AS non_nx,
       count(*) AS total
FROM public.stores;
